apiVersion: v1
kind: Service
metadata:
  name: open5gs-webui
  namespace: open5gs
  labels:
    epc-mode: webui
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    epc-mode: webui
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-webui
  namespace: open5gs  
  labels:
    epc-mode: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      epc-mode: webui
  template:
    metadata:
      labels:
        epc-mode: webui
    spec:
      containers:
      - name: webui
        #imagePullPolicy: Always
        image: registry.gitlab.com/infinitydon/registry/open5gs-webui:1.2.0
        command: ["node", "server/index.js"]
        env:
        - name: DB_URI
          value: "mongodb://mongodb/open5gs?replicaSet=rs0"
        - name: NODE_ENV
          value: "production"          